# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/josh/Dropbox/Python/Feather_Labs_Suite/FLS5/Launch/FLS_5.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(660, 525)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(660, 525))
        MainWindow.setMaximumSize(QtCore.QSize(660, 525))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/josh/Dropbox/Python/Feather_Labs_Suite/FLS5/Launch/../favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, 0, 681, 355))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_1 = QtWidgets.QWidget()
        self.Tab_1.setObjectName("Tab_1")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Tab_1)
        self.tabWidget_2.setGeometry(QtCore.QRect(-2, 0, 681, 322))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.t1t1 = QtWidgets.QWidget()
        self.t1t1.setObjectName("t1t1")
        self.t1l1 = QtWidgets.QLabel(self.t1t1)
        self.t1l1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t1l1.setObjectName("t1l1")
        self.t1l2 = QtWidgets.QLabel(self.t1t1)
        self.t1l2.setGeometry(QtCore.QRect(10, 129, 111, 25))
        self.t1l2.setObjectName("t1l2")
        self.t1l3 = QtWidgets.QLabel(self.t1t1)
        self.t1l3.setGeometry(QtCore.QRect(10, 85, 91, 25))
        self.t1l3.setObjectName("t1l3")
        self.t1l4 = QtWidgets.QLabel(self.t1t1)
        self.t1l4.setGeometry(QtCore.QRect(10, 45, 111, 25))
        self.t1l4.setObjectName("t1l4")
        self.t1l5 = QtWidgets.QLabel(self.t1t1)
        self.t1l5.setGeometry(QtCore.QRect(10, 165, 81, 25))
        self.t1l5.setObjectName("t1l5")
        self.t1de = QtWidgets.QLineEdit(self.t1t1)
        self.t1de.setGeometry(QtCore.QRect(160, 10, 145, 25))
        self.t1de.setObjectName("t1de")
        self.Chk_drop = QtWidgets.QComboBox(self.t1t1)
        self.Chk_drop.setGeometry(QtCore.QRect(160, 124, 145, 34))
        self.Chk_drop.setObjectName("Chk_drop")
        self.Chk_drop.addItem("")
        self.Chk_drop.addItem("")
        self.Chk_drop.addItem("")
        self.Scr_drop = QtWidgets.QComboBox(self.t1t1)
        self.Scr_drop.setGeometry(QtCore.QRect(160, 80, 145, 34))
        self.Scr_drop.setObjectName("Scr_drop")
        self.Scr_drop.addItem("")
        self.Scr_drop.addItem("")
        self.Scr_drop.addItem("")
        self.Scr_drop.addItem("")
        self.Rwf_drop = QtWidgets.QComboBox(self.t1t1)
        self.Rwf_drop.setGeometry(QtCore.QRect(160, 40, 145, 34))
        self.Rwf_drop.setObjectName("Rwf_drop")
        self.Rwf_drop.addItem("")
        self.Rwf_drop.addItem("")
        self.Rwf_drop.addItem("")
        self.Rwf_drop.addItem("")
        self.gusr_entry = QtWidgets.QLineEdit(self.t1t1)
        self.gusr_entry.setEnabled(False)
        self.gusr_entry.setGeometry(QtCore.QRect(160, 170, 145, 25))
        self.gusr_entry.setObjectName("gusr_entry")
        self.t1l6 = QtWidgets.QLabel(self.t1t1)
        self.t1l6.setGeometry(QtCore.QRect(350, 10, 60, 25))
        self.t1l6.setObjectName("t1l6")
        self.basis_entry = QtWidgets.QLineEdit(self.t1t1)
        self.basis_entry.setGeometry(QtCore.QRect(470, 10, 175, 25))
        self.basis_entry.setObjectName("basis_entry")
        self.t1l7 = QtWidgets.QLabel(self.t1t1)
        self.t1l7.setGeometry(QtCore.QRect(350, 40, 80, 25))
        self.t1l7.setObjectName("t1l7")
        self.t1l9 = QtWidgets.QLabel(self.t1t1)
        self.t1l9.setGeometry(QtCore.QRect(350, 100, 80, 25))
        self.t1l9.setObjectName("t1l9")
        self.t1l8 = QtWidgets.QLabel(self.t1t1)
        self.t1l8.setGeometry(QtCore.QRect(350, 70, 91, 25))
        self.t1l8.setObjectName("t1l8")
        self.t1l10 = QtWidgets.QLabel(self.t1t1)
        self.t1l10.setGeometry(QtCore.QRect(350, 130, 81, 25))
        self.t1l10.setObjectName("t1l10")
        self.proc_entry = QtWidgets.QSpinBox(self.t1t1)
        self.proc_entry.setGeometry(QtCore.QRect(470, 40, 175, 25))
        self.proc_entry.setMaximum(32)
        self.proc_entry.setProperty("value", 4)
        self.proc_entry.setObjectName("proc_entry")
        self.mem_entry = QtWidgets.QSpinBox(self.t1t1)
        self.mem_entry.setGeometry(QtCore.QRect(470, 70, 175, 25))
        self.mem_entry.setMaximum(128000)
        self.mem_entry.setProperty("value", 4500)
        self.mem_entry.setObjectName("mem_entry")
        self.CHARGE_entry = QtWidgets.QSpinBox(self.t1t1)
        self.CHARGE_entry.setGeometry(QtCore.QRect(470, 100, 175, 25))
        self.CHARGE_entry.setMinimum(-99)
        self.CHARGE_entry.setMaximum(99)
        self.CHARGE_entry.setProperty("value", 0)
        self.CHARGE_entry.setObjectName("CHARGE_entry")
        self.Multi_entry = QtWidgets.QSpinBox(self.t1t1)
        self.Multi_entry.setGeometry(QtCore.QRect(470, 130, 175, 25))
        self.Multi_entry.setMinimum(-99)
        self.Multi_entry.setMaximum(99)
        self.Multi_entry.setProperty("value", 0)
        self.Multi_entry.setObjectName("Multi_entry")
        self.t1l11 = QtWidgets.QLabel(self.t1t1)
        self.t1l11.setGeometry(QtCore.QRect(10, 200, 91, 25))
        self.t1l11.setObjectName("t1l11")
        self.foot_drop = QtWidgets.QComboBox(self.t1t1)
        self.foot_drop.setGeometry(QtCore.QRect(10, 230, 104, 34))
        self.foot_drop.setObjectName("foot_drop")
        self.foot_drop.addItem("")
        self.foot_drop.addItem("")
        self.foote = QtWidgets.QTextEdit(self.t1t1)
        self.foote.setGeometry(QtCore.QRect(120, 200, 525, 83))
        self.foote.setObjectName("foote")
        self.tabWidget_2.addTab(self.t1t1, "")
        self.t1t2 = QtWidgets.QWidget()
        self.t1t2.setObjectName("t1t2")
        self.t1t2l04 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l04.setGeometry(QtCore.QRect(10, 45, 111, 25))
        self.t1t2l04.setObjectName("t1t2l04")
        self.t1t2l03 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l03.setGeometry(QtCore.QRect(10, 85, 81, 25))
        self.t1t2l03.setObjectName("t1t2l03")
        self.Scr_drop_2 = QtWidgets.QComboBox(self.t1t2)
        self.Scr_drop_2.setGeometry(QtCore.QRect(160, 80, 145, 34))
        self.Scr_drop_2.setObjectName("Scr_drop_2")
        self.Scr_drop_2.addItem("")
        self.Scr_drop_2.addItem("")
        self.Scr_drop_2.addItem("")
        self.Scr_drop_2.addItem("")
        self.t1t2l01 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l01.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t1t2l01.setObjectName("t1t2l01")
        self.t1de_2 = QtWidgets.QLineEdit(self.t1t2)
        self.t1de_2.setGeometry(QtCore.QRect(160, 10, 145, 25))
        self.t1de_2.setObjectName("t1de_2")
        self.foote_2 = QtWidgets.QTextEdit(self.t1t2)
        self.foote_2.setGeometry(QtCore.QRect(120, 200, 525, 83))
        self.foote_2.setObjectName("foote_2")
        self.t1t2l07 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l07.setGeometry(QtCore.QRect(350, 70, 80, 25))
        self.t1t2l07.setObjectName("t1t2l07")
        self.t1t2l02 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l02.setGeometry(QtCore.QRect(10, 129, 121, 25))
        self.t1t2l02.setObjectName("t1t2l02")
        self.t1t2l05 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l05.setGeometry(QtCore.QRect(10, 165, 81, 25))
        self.t1t2l05.setObjectName("t1t2l05")
        self.t1t2l11 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l11.setGeometry(QtCore.QRect(10, 200, 81, 25))
        self.t1t2l11.setObjectName("t1t2l11")
        self.Chk_drop_2 = QtWidgets.QComboBox(self.t1t2)
        self.Chk_drop_2.setGeometry(QtCore.QRect(160, 124, 145, 34))
        self.Chk_drop_2.setObjectName("Chk_drop_2")
        self.Chk_drop_2.addItem("")
        self.Chk_drop_2.addItem("")
        self.Chk_drop_2.addItem("")
        self.Multi_entry_2 = QtWidgets.QSpinBox(self.t1t2)
        self.Multi_entry_2.setGeometry(QtCore.QRect(470, 160, 175, 25))
        self.Multi_entry_2.setMinimum(-99)
        self.Multi_entry_2.setMaximum(99)
        self.Multi_entry_2.setProperty("value", 0)
        self.Multi_entry_2.setObjectName("Multi_entry_2")
        self.mem_entry_2 = QtWidgets.QSpinBox(self.t1t2)
        self.mem_entry_2.setGeometry(QtCore.QRect(470, 100, 175, 25))
        self.mem_entry_2.setMaximum(128000)
        self.mem_entry_2.setProperty("value", 4500)
        self.mem_entry_2.setObjectName("mem_entry_2")
        self.t1t2l06 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l06.setGeometry(QtCore.QRect(350, 40, 60, 25))
        self.t1t2l06.setObjectName("t1t2l06")
        self.proc_entry_2 = QtWidgets.QSpinBox(self.t1t2)
        self.proc_entry_2.setGeometry(QtCore.QRect(470, 70, 175, 25))
        self.proc_entry_2.setMaximum(32)
        self.proc_entry_2.setProperty("value", 4)
        self.proc_entry_2.setObjectName("proc_entry_2")
        self.basis_entry_2 = QtWidgets.QLineEdit(self.t1t2)
        self.basis_entry_2.setGeometry(QtCore.QRect(470, 40, 175, 25))
        self.basis_entry_2.setObjectName("basis_entry_2")
        self.Rwf_drop_2 = QtWidgets.QComboBox(self.t1t2)
        self.Rwf_drop_2.setGeometry(QtCore.QRect(160, 40, 145, 34))
        self.Rwf_drop_2.setObjectName("Rwf_drop_2")
        self.Rwf_drop_2.addItem("")
        self.Rwf_drop_2.addItem("")
        self.Rwf_drop_2.addItem("")
        self.Rwf_drop_2.addItem("")
        self.t1t2l09 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l09.setGeometry(QtCore.QRect(350, 130, 80, 25))
        self.t1t2l09.setObjectName("t1t2l09")
        self.CHARGE_entry_2 = QtWidgets.QSpinBox(self.t1t2)
        self.CHARGE_entry_2.setGeometry(QtCore.QRect(470, 130, 175, 25))
        self.CHARGE_entry_2.setMinimum(-99)
        self.CHARGE_entry_2.setMaximum(99)
        self.CHARGE_entry_2.setProperty("value", 0)
        self.CHARGE_entry_2.setObjectName("CHARGE_entry_2")
        self.t1t2l10 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l10.setGeometry(QtCore.QRect(350, 160, 81, 25))
        self.t1t2l10.setObjectName("t1t2l10")
        self.t1t2l08 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l08.setGeometry(QtCore.QRect(350, 100, 101, 25))
        self.t1t2l08.setObjectName("t1t2l08")
        self.gusr_entry_2 = QtWidgets.QLineEdit(self.t1t2)
        self.gusr_entry_2.setEnabled(False)
        self.gusr_entry_2.setGeometry(QtCore.QRect(160, 170, 145, 25))
        self.gusr_entry_2.setObjectName("gusr_entry_2")
        self.t1t2l12 = QtWidgets.QLabel(self.t1t2)
        self.t1t2l12.setGeometry(QtCore.QRect(350, 7, 101, 25))
        self.t1t2l12.setObjectName("t1t2l12")
        self.t1t2CB_1 = QtWidgets.QComboBox(self.t1t2)
        self.t1t2CB_1.setGeometry(QtCore.QRect(470, 2, 175, 34))
        self.t1t2CB_1.setObjectName("t1t2CB_1")
        self.t1t2CB_1.addItem("")
        self.t1t2CB_1.addItem("")
        self.t1t2CB_1.addItem("")
        self.tabWidget_2.addTab(self.t1t2, "")
        self.t1t3 = QtWidgets.QWidget()
        self.t1t3.setObjectName("t1t3")
        self.t1t3le_1 = QtWidgets.QLineEdit(self.t1t3)
        self.t1t3le_1.setGeometry(QtCore.QRect(120, 10, 525, 25))
        self.t1t3le_1.setObjectName("t1t3le_1")
        self.t1t3l_1 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t1t3l_1.setObjectName("t1t3l_1")
        self.t1t3l_2 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_2.setGeometry(QtCore.QRect(10, 44, 91, 25))
        self.t1t3l_2.setObjectName("t1t3l_2")
        self.t1t3l_3 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_3.setGeometry(QtCore.QRect(10, 80, 101, 25))
        self.t1t3l_3.setObjectName("t1t3l_3")
        self.t1t3le_2 = QtWidgets.QLineEdit(self.t1t3)
        self.t1t3le_2.setGeometry(QtCore.QRect(120, 44, 525, 25))
        self.t1t3le_2.setObjectName("t1t3le_2")
        self.t1t3le_3 = QtWidgets.QLineEdit(self.t1t3)
        self.t1t3le_3.setGeometry(QtCore.QRect(120, 80, 525, 25))
        self.t1t3le_3.setObjectName("t1t3le_3")
        self.t1t3l_4 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_4.setGeometry(QtCore.QRect(250, 120, 121, 25))
        self.t1t3l_4.setObjectName("t1t3l_4")
        self.t1t3le_4 = QtWidgets.QLineEdit(self.t1t3)
        self.t1t3le_4.setGeometry(QtCore.QRect(200, 150, 445, 25))
        self.t1t3le_4.setObjectName("t1t3le_4")
        self.t1t3le_5 = QtWidgets.QLineEdit(self.t1t3)
        self.t1t3le_5.setGeometry(QtCore.QRect(200, 184, 445, 25))
        self.t1t3le_5.setObjectName("t1t3le_5")
        self.t1t3l_5 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_5.setGeometry(QtCore.QRect(10, 150, 161, 25))
        self.t1t3l_5.setObjectName("t1t3l_5")
        self.t1t3l_6 = QtWidgets.QLabel(self.t1t3)
        self.t1t3l_6.setGeometry(QtCore.QRect(10, 184, 171, 25))
        self.t1t3l_6.setObjectName("t1t3l_6")
        self.tabWidget_2.addTab(self.t1t3, "")
        self.tabWidget.addTab(self.Tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 671, 301))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.t2t1 = QtWidgets.QWidget()
        self.t2t1.setObjectName("t2t1")
        self.t2t1l_2 = QtWidgets.QLabel(self.t2t1)
        self.t2t1l_2.setGeometry(QtCore.QRect(10, 44, 131, 25))
        self.t2t1l_2.setObjectName("t2t1l_2")
        self.t2t1l_4 = QtWidgets.QLabel(self.t2t1)
        self.t2t1l_4.setGeometry(QtCore.QRect(10, 124, 131, 25))
        self.t2t1l_4.setObjectName("t2t1l_4")
        self.t2t1l_1 = QtWidgets.QLabel(self.t2t1)
        self.t2t1l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t2t1l_1.setObjectName("t2t1l_1")
        self.t2t1l_3 = QtWidgets.QLabel(self.t2t1)
        self.t2t1l_3.setGeometry(QtCore.QRect(10, 84, 141, 25))
        self.t2t1l_3.setObjectName("t2t1l_3")
        self.t2t1l_5 = QtWidgets.QLabel(self.t2t1)
        self.t2t1l_5.setGeometry(QtCore.QRect(10, 165, 141, 25))
        self.t2t1l_5.setObjectName("t2t1l_5")
        self.t2t1LE_1 = QtWidgets.QLineEdit(self.t2t1)
        self.t2t1LE_1.setGeometry(QtCore.QRect(160, 10, 475, 25))
        self.t2t1LE_1.setObjectName("t2t1LE_1")
        self.t2t1CB_1 = QtWidgets.QComboBox(self.t2t1)
        self.t2t1CB_1.setGeometry(QtCore.QRect(160, 40, 71, 34))
        self.t2t1CB_1.setObjectName("t2t1CB_1")
        self.t2t1CB_1.addItem("")
        self.t2t1CB_1.addItem("")
        self.t2t1CB_2 = QtWidgets.QComboBox(self.t2t1)
        self.t2t1CB_2.setGeometry(QtCore.QRect(160, 80, 71, 34))
        self.t2t1CB_2.setObjectName("t2t1CB_2")
        self.t2t1CB_2.addItem("")
        self.t2t1CB_2.addItem("")
        self.t2t1CB_3 = QtWidgets.QComboBox(self.t2t1)
        self.t2t1CB_3.setGeometry(QtCore.QRect(160, 120, 71, 34))
        self.t2t1CB_3.setObjectName("t2t1CB_3")
        self.t2t1CB_3.addItem("")
        self.t2t1CB_3.addItem("")
        self.t2t1CB_4 = QtWidgets.QComboBox(self.t2t1)
        self.t2t1CB_4.setGeometry(QtCore.QRect(160, 160, 71, 34))
        self.t2t1CB_4.setObjectName("t2t1CB_4")
        self.t2t1CB_4.addItem("")
        self.t2t1CB_4.addItem("")
        self.tabWidget_3.addTab(self.t2t1, "")
        self.t2t11 = QtWidgets.QWidget()
        self.t2t11.setObjectName("t2t11")
        self.t2t2l_1 = QtWidgets.QLabel(self.t2t11)
        self.t2t2l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t2t2l_1.setObjectName("t2t2l_1")
        self.t2t2LE_1 = QtWidgets.QLineEdit(self.t2t11)
        self.t2t2LE_1.setGeometry(QtCore.QRect(160, 10, 475, 25))
        self.t2t2LE_1.setObjectName("t2t2LE_1")
        self.t2t2l_2 = QtWidgets.QLabel(self.t2t11)
        self.t2t2l_2.setGeometry(QtCore.QRect(10, 92, 131, 25))
        self.t2t2l_2.setObjectName("t2t2l_2")
        self.t2t2CB_2 = QtWidgets.QComboBox(self.t2t11)
        self.t2t2CB_2.setGeometry(QtCore.QRect(160, 86, 71, 34))
        self.t2t2CB_2.setObjectName("t2t2CB_2")
        self.t2t2CB_2.addItem("")
        self.t2t2CB_2.addItem("")
        self.t2t2l_3 = QtWidgets.QLabel(self.t2t11)
        self.t2t2l_3.setGeometry(QtCore.QRect(10, 49, 91, 25))
        self.t2t2l_3.setObjectName("t2t2l_3")
        self.t2t2CB_1 = QtWidgets.QComboBox(self.t2t11)
        self.t2t2CB_1.setGeometry(QtCore.QRect(160, 43, 175, 34))
        self.t2t2CB_1.setObjectName("t2t2CB_1")
        self.t2t2CB_1.addItem("")
        self.t2t2CB_1.addItem("")
        self.t2t2l_4 = QtWidgets.QLabel(self.t2t11)
        self.t2t2l_4.setGeometry(QtCore.QRect(10, 138, 91, 20))
        self.t2t2l_4.setObjectName("t2t2l_4")
        self.t2t2CB_3 = QtWidgets.QComboBox(self.t2t11)
        self.t2t2CB_3.setGeometry(QtCore.QRect(160, 127, 118, 34))
        self.t2t2CB_3.setObjectName("t2t2CB_3")
        self.t2t2CB_3.addItem("")
        self.t2t2CB_3.addItem("")
        self.t2t2CB_3.addItem("")
        self.t2t2CB_3.addItem("")
        self.t2t2l_5 = QtWidgets.QLabel(self.t2t11)
        self.t2t2l_5.setGeometry(QtCore.QRect(10, 180, 131, 20))
        self.t2t2l_5.setObjectName("t2t2l_5")
        self.t2t2CB_4 = QtWidgets.QComboBox(self.t2t11)
        self.t2t2CB_4.setEnabled(False)
        self.t2t2CB_4.setGeometry(QtCore.QRect(160, 170, 71, 34))
        self.t2t2CB_4.setObjectName("t2t2CB_4")
        self.t2t2CB_4.addItem("")
        self.t2t2CB_4.addItem("")
        self.tabWidget_3.addTab(self.t2t11, "")
        self.t2t3 = QtWidgets.QWidget()
        self.t2t3.setObjectName("t2t3")
        self.t2t3LE_1 = QtWidgets.QLineEdit(self.t2t3)
        self.t2t3LE_1.setGeometry(QtCore.QRect(160, 10, 475, 25))
        self.t2t3LE_1.setObjectName("t2t3LE_1")
        self.t2t3l_1 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t2t3l_1.setObjectName("t2t3l_1")
        self.t2t3l_4 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_4.setGeometry(QtCore.QRect(10, 115, 80, 25))
        self.t2t3l_4.setObjectName("t2t3l_4")
        self.t2t3l_3 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_3.setGeometry(QtCore.QRect(10, 80, 91, 25))
        self.t2t3l_3.setObjectName("t2t3l_3")
        self.t2t3SB_2 = QtWidgets.QSpinBox(self.t2t3)
        self.t2t3SB_2.setGeometry(QtCore.QRect(160, 80, 145, 25))
        self.t2t3SB_2.setMaximum(4000)
        self.t2t3SB_2.setProperty("value", 600)
        self.t2t3SB_2.setObjectName("t2t3SB_2")
        self.t2t3l_2 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_2.setGeometry(QtCore.QRect(10, 45, 80, 25))
        self.t2t3l_2.setObjectName("t2t3l_2")
        self.t2t3SB_1 = QtWidgets.QSpinBox(self.t2t3)
        self.t2t3SB_1.setGeometry(QtCore.QRect(160, 45, 145, 25))
        self.t2t3SB_1.setMinimum(1)
        self.t2t3SB_1.setMaximum(100)
        self.t2t3SB_1.setProperty("value", 1)
        self.t2t3SB_1.setObjectName("t2t3SB_1")
        self.t2t3SB_4 = QtWidgets.QSpinBox(self.t2t3)
        self.t2t3SB_4.setGeometry(QtCore.QRect(160, 115, 145, 25))
        self.t2t3SB_4.setMinimum(1)
        self.t2t3SB_4.setMaximum(100)
        self.t2t3SB_4.setProperty("value", 4)
        self.t2t3SB_4.setObjectName("t2t3SB_4")
        self.t2t3CB_1 = QtWidgets.QComboBox(self.t2t3)
        self.t2t3CB_1.setGeometry(QtCore.QRect(159, 147, 120, 34))
        self.t2t3CB_1.setObjectName("t2t3CB_1")
        self.t2t3CB_1.addItem("")
        self.t2t3CB_1.addItem("")
        self.t2t3CB_2 = QtWidgets.QComboBox(self.t2t3)
        self.t2t3CB_2.setGeometry(QtCore.QRect(159, 188, 71, 34))
        self.t2t3CB_2.setObjectName("t2t3CB_2")
        self.t2t3CB_2.addItem("")
        self.t2t3CB_2.addItem("")
        self.t2t3l_5 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_5.setGeometry(QtCore.QRect(9, 152, 111, 25))
        self.t2t3l_5.setObjectName("t2t3l_5")
        self.t2t3l_6 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_6.setGeometry(QtCore.QRect(10, 193, 121, 25))
        self.t2t3l_6.setObjectName("t2t3l_6")
        self.t2t3SB_3 = QtWidgets.QSpinBox(self.t2t3)
        self.t2t3SB_3.setGeometry(QtCore.QRect(490, 79, 145, 25))
        self.t2t3SB_3.setMaximum(4000)
        self.t2t3SB_3.setProperty("value", 2400)
        self.t2t3SB_3.setObjectName("t2t3SB_3")
        self.t2t3l_7 = QtWidgets.QLabel(self.t2t3)
        self.t2t3l_7.setGeometry(QtCore.QRect(358, 79, 111, 25))
        self.t2t3l_7.setObjectName("t2t3l_7")
        self.tabWidget_3.addTab(self.t2t3, "")
        self.t2t4 = QtWidgets.QWidget()
        self.t2t4.setObjectName("t2t4")
        self.t2t4l_3 = QtWidgets.QLabel(self.t2t4)
        self.t2t4l_3.setGeometry(QtCore.QRect(10, 87, 111, 25))
        self.t2t4l_3.setObjectName("t2t4l_3")
        self.t2t4SB_1 = QtWidgets.QSpinBox(self.t2t4)
        self.t2t4SB_1.setGeometry(QtCore.QRect(160, 87, 61, 25))
        self.t2t4SB_1.setMinimum(1)
        self.t2t4SB_1.setMaximum(360)
        self.t2t4SB_1.setProperty("value", 2)
        self.t2t4SB_1.setObjectName("t2t4SB_1")
        self.t2t4LE_1 = QtWidgets.QLineEdit(self.t2t4)
        self.t2t4LE_1.setGeometry(QtCore.QRect(160, 10, 371, 25))
        self.t2t4LE_1.setObjectName("t2t4LE_1")
        self.t2t4CB_1 = QtWidgets.QComboBox(self.t2t4)
        self.t2t4CB_1.setGeometry(QtCore.QRect(160, 43, 47, 34))
        self.t2t4CB_1.setObjectName("t2t4CB_1")
        self.t2t4CB_1.addItem("")
        self.t2t4CB_1.addItem("")
        self.t2t4CB_1.addItem("")
        self.t2t4l_2 = QtWidgets.QLabel(self.t2t4)
        self.t2t4l_2.setGeometry(QtCore.QRect(10, 47, 91, 25))
        self.t2t4l_2.setObjectName("t2t4l_2")
        self.t2t4l_1 = QtWidgets.QLabel(self.t2t4)
        self.t2t4l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t2t4l_1.setObjectName("t2t4l_1")
        self.t2t4PB_1 = QtWidgets.QPushButton(self.t2t4)
        self.t2t4PB_1.setGeometry(QtCore.QRect(540, 10, 101, 25))
        self.t2t4PB_1.setObjectName("t2t4PB_1")
        self.tabWidget_3.addTab(self.t2t4, "")
        self.t2t5 = QtWidgets.QWidget()
        self.t2t5.setObjectName("t2t5")
        self.t2t5CB_2 = QtWidgets.QComboBox(self.t2t5)
        self.t2t5CB_2.setGeometry(QtCore.QRect(120, 41, 175, 34))
        self.t2t5CB_2.setObjectName("t2t5CB_2")
        self.t2t5CB_2.addItem("")
        self.t2t5CB_2.addItem("")
        self.t2t5CB_1 = QtWidgets.QComboBox(self.t2t5)
        self.t2t5CB_1.setGeometry(QtCore.QRect(120, 80, 61, 34))
        self.t2t5CB_1.setObjectName("t2t5CB_1")
        self.t2t5CB_1.addItem("")
        self.t2t5CB_1.addItem("")
        self.t2t5LE_1 = QtWidgets.QLineEdit(self.t2t5)
        self.t2t5LE_1.setGeometry(QtCore.QRect(120, 10, 521, 25))
        self.t2t5LE_1.setObjectName("t2t5LE_1")
        self.t2t5l_2 = QtWidgets.QLabel(self.t2t5)
        self.t2t5l_2.setGeometry(QtCore.QRect(10, 46, 91, 25))
        self.t2t5l_2.setObjectName("t2t5l_2")
        self.t2t5l_1 = QtWidgets.QLabel(self.t2t5)
        self.t2t5l_1.setGeometry(QtCore.QRect(10, 10, 60, 25))
        self.t2t5l_1.setObjectName("t2t5l_1")
        self.t2t5l_3 = QtWidgets.QLabel(self.t2t5)
        self.t2t5l_3.setGeometry(QtCore.QRect(10, 87, 101, 25))
        self.t2t5l_3.setObjectName("t2t5l_3")
        self.tabWidget_3.addTab(self.t2t5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.t3PSB_3 = QtWidgets.QSpinBox(self.tab)
        self.t3PSB_3.setGeometry(QtCore.QRect(505, 82, 145, 25))
        self.t3PSB_3.setMinimum(-99)
        self.t3PSB_3.setMaximum(99)
        self.t3PSB_3.setProperty("value", 1)
        self.t3PSB_3.setObjectName("t3PSB_3")
        self.t3PQB_3 = QtWidgets.QComboBox(self.tab)
        self.t3PQB_3.setGeometry(QtCore.QRect(180, 90, 142, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3PQB_3.sizePolicy().hasHeightForWidth())
        self.t3PQB_3.setSizePolicy(sizePolicy)
        self.t3PQB_3.setStyleSheet("")
        self.t3PQB_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.t3PQB_3.setMinimumContentsLength(0)
        self.t3PQB_3.setFrame(True)
        self.t3PQB_3.setObjectName("t3PQB_3")
        self.t3PQB_3.addItem("")
        self.t3PQB_3.addItem("")
        self.t3PQB_3.addItem("")
        self.t3PQB_3.addItem("")
        self.t1l7_2 = QtWidgets.QLabel(self.tab)
        self.t1l7_2.setGeometry(QtCore.QRect(380, 10, 91, 25))
        self.t1l7_2.setObjectName("t1l7_2")
        self.t3PSB_1 = QtWidgets.QSpinBox(self.tab)
        self.t3PSB_1.setGeometry(QtCore.QRect(505, 10, 145, 25))
        self.t3PSB_1.setMaximum(32)
        self.t3PSB_1.setProperty("value", 8)
        self.t3PSB_1.setObjectName("t3PSB_1")
        self.t1l8_2 = QtWidgets.QLabel(self.tab)
        self.t1l8_2.setGeometry(QtCore.QRect(380, 46, 91, 25))
        self.t1l8_2.setObjectName("t1l8_2")
        self.t3PQB_2 = QtWidgets.QComboBox(self.tab)
        self.t3PQB_2.setGeometry(QtCore.QRect(180, 50, 142, 34))
        self.t3PQB_2.setObjectName("t3PQB_2")
        self.t3PQB_2.addItem("")
        self.t3PQB_2.addItem("")
        self.t3PQB_2.addItem("")
        self.t3PQB_2.addItem("")
        self.t1l10_2 = QtWidgets.QLabel(self.tab)
        self.t1l10_2.setGeometry(QtCore.QRect(380, 119, 91, 25))
        self.t1l10_2.setObjectName("t1l10_2")
        self.t3PSB_2 = QtWidgets.QSpinBox(self.tab)
        self.t3PSB_2.setGeometry(QtCore.QRect(505, 46, 145, 25))
        self.t3PSB_2.setMaximum(128000)
        self.t3PSB_2.setProperty("value", 4500)
        self.t3PSB_2.setObjectName("t3PSB_2")
        self.t1l5_2 = QtWidgets.QLabel(self.tab)
        self.t1l5_2.setGeometry(QtCore.QRect(20, 130, 81, 25))
        self.t1l5_2.setObjectName("t1l5_2")
        self.t3PQB_1 = QtWidgets.QComboBox(self.tab)
        self.t3PQB_1.setGeometry(QtCore.QRect(180, 10, 142, 34))
        self.t3PQB_1.setObjectName("t3PQB_1")
        self.t3PQB_1.addItem("")
        self.t3PQB_1.addItem("")
        self.t3PQB_1.addItem("")
        self.t1l9_2 = QtWidgets.QLabel(self.tab)
        self.t1l9_2.setGeometry(QtCore.QRect(380, 82, 91, 25))
        self.t1l9_2.setObjectName("t1l9_2")
        self.t3PLE_1 = QtWidgets.QLineEdit(self.tab)
        self.t3PLE_1.setEnabled(True)
        self.t3PLE_1.setGeometry(QtCore.QRect(180, 130, 142, 25))
        self.t3PLE_1.setObjectName("t3PLE_1")
        self.t1l2_2 = QtWidgets.QLabel(self.tab)
        self.t1l2_2.setGeometry(QtCore.QRect(20, 93, 111, 25))
        self.t1l2_2.setObjectName("t1l2_2")
        self.t1l4_2 = QtWidgets.QLabel(self.tab)
        self.t1l4_2.setGeometry(QtCore.QRect(21, 15, 111, 25))
        self.t1l4_2.setObjectName("t1l4_2")
        self.t3PSB_4 = QtWidgets.QSpinBox(self.tab)
        self.t3PSB_4.setGeometry(QtCore.QRect(505, 119, 145, 25))
        self.t3PSB_4.setMinimum(-99)
        self.t3PSB_4.setMaximum(99)
        self.t3PSB_4.setProperty("value", 1)
        self.t3PSB_4.setObjectName("t3PSB_4")
        self.t1l3_2 = QtWidgets.QLabel(self.tab)
        self.t1l3_2.setGeometry(QtCore.QRect(20, 53, 91, 25))
        self.t1l3_2.setObjectName("t1l3_2")
        self.t3PQB_4 = QtWidgets.QComboBox(self.tab)
        self.t3PQB_4.setGeometry(QtCore.QRect(180, 160, 142, 34))
        self.t3PQB_4.setObjectName("t3PQB_4")
        self.t3PQB_4.addItem("")
        self.t1l4_3 = QtWidgets.QLabel(self.tab)
        self.t1l4_3.setGeometry(QtCore.QRect(20, 163, 80, 25))
        self.t1l4_3.setObjectName("t1l4_3")
        self.t3PPTE_1 = QtWidgets.QPlainTextEdit(self.tab)
        self.t3PPTE_1.setGeometry(QtCore.QRect(20, 200, 630, 91))
        self.t3PPTE_1.setReadOnly(False)
        self.t3PPTE_1.setObjectName("t3PPTE_1")
        self.tabWidget.addTab(self.tab, "")
        self.Console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Console.setGeometry(QtCore.QRect(5, 390, 650, 101))
        self.Console.setReadOnly(True)
        self.Console.setObjectName("Console")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 360, 93, 25))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 360, 541, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.action_Change_Log = QtWidgets.QAction(MainWindow)
        self.action_Change_Log.setObjectName("action_Change_Log")
        self.action_Check_for_updates = QtWidgets.QAction(MainWindow)
        self.action_Check_for_updates.setObjectName("action_Check_for_updates")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.action_Check_for_updates)
        self.menuFile.addAction(self.action_Exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Feather Labs Suite 1.0.0"))
        self.t1l1.setText(_translate("MainWindow", "Directory"))
        self.t1l2.setText(_translate("MainWindow", "Checkpoint File"))
        self.t1l3.setText(_translate("MainWindow", "Scratch File"))
        self.t1l4.setText(_translate("MainWindow", "Read Write File"))
        self.t1l5.setText(_translate("MainWindow", "Username"))
        self.Chk_drop.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Chk_drop.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Chk_drop.setItemText(2, _translate("MainWindow", "/scratch/chk"))
        self.Scr_drop.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Scr_drop.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Scr_drop.setItemText(2, _translate("MainWindow", "/scratch/scr"))
        self.Scr_drop.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.Rwf_drop.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Rwf_drop.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Rwf_drop.setItemText(2, _translate("MainWindow", "/scratch/rwf"))
        self.Rwf_drop.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.t1l6.setText(_translate("MainWindow", "Basis set"))
        self.t1l7.setText(_translate("MainWindow", "Processors"))
        self.t1l9.setText(_translate("MainWindow", "Charge"))
        self.t1l8.setText(_translate("MainWindow", "Memory (MB)"))
        self.t1l10.setText(_translate("MainWindow", "Multiplicity"))
        self.t1l11.setText(_translate("MainWindow", "Footer Info"))
        self.foot_drop.setItemText(0, _translate("MainWindow", "Append"))
        self.foot_drop.setItemText(1, _translate("MainWindow", "Overwrite"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.t1t1), _translate("MainWindow", "Modify Input Files"))
        self.t1t2l04.setText(_translate("MainWindow", "Read Write File"))
        self.t1t2l03.setText(_translate("MainWindow", "Scratch File"))
        self.Scr_drop_2.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Scr_drop_2.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Scr_drop_2.setItemText(2, _translate("MainWindow", "/scratch/scr"))
        self.Scr_drop_2.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.t1t2l01.setText(_translate("MainWindow", "Directory"))
        self.foote_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.t1t2l07.setText(_translate("MainWindow", "Processors"))
        self.t1t2l02.setText(_translate("MainWindow", "Checkpoint File"))
        self.t1t2l05.setText(_translate("MainWindow", "Username"))
        self.t1t2l11.setText(_translate("MainWindow", "Footer Info"))
        self.Chk_drop_2.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Chk_drop_2.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Chk_drop_2.setItemText(2, _translate("MainWindow", "/scratch/chk"))
        self.t1t2l06.setText(_translate("MainWindow", "Basis set"))
        self.Rwf_drop_2.setItemText(0, _translate("MainWindow", "Do not save"))
        self.Rwf_drop_2.setItemText(1, _translate("MainWindow", "Same directory"))
        self.Rwf_drop_2.setItemText(2, _translate("MainWindow", "/scratch/rwf"))
        self.Rwf_drop_2.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.t1t2l09.setText(_translate("MainWindow", "Charge"))
        self.t1t2l10.setText(_translate("MainWindow", "Multiplicity"))
        self.t1t2l08.setText(_translate("MainWindow", "Memory (MB)"))
        self.t1t2l12.setText(_translate("MainWindow", "Status of Jobs"))
        self.t1t2CB_1.setItemText(0, _translate("MainWindow", "Successful"))
        self.t1t2CB_1.setItemText(1, _translate("MainWindow", "Succesful & Imaginary"))
        self.t1t2CB_1.setItemText(2, _translate("MainWindow", "Sucessful & Failed"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.t1t2), _translate("MainWindow", "Convert Output to Input"))
        self.t1t3l_1.setText(_translate("MainWindow", "Directory"))
        self.t1t3l_2.setText(_translate("MainWindow", "Search For"))
        self.t1t3l_3.setText(_translate("MainWindow", "Replace With"))
        self.t1t3le_2.setPlaceholderText(_translate("MainWindow", "The keyword you would like to replace in the filename (i.e _OPT)"))
        self.t1t3le_3.setPlaceholderText(_translate("MainWindow", "The keyword you would like to replace with the filename (i.e _FREQ)"))
        self.t1t3l_4.setText(_translate("MainWindow", "Optional Settings"))
        self.t1t3le_4.setPlaceholderText(_translate("MainWindow", "Specify a file extension here to edit files of that type (i.e .gjf)"))
        self.t1t3le_5.setPlaceholderText(_translate("MainWindow", "Specify a file extension here to change files to that type (i.e .gjf)"))
        self.t1t3l_5.setText(_translate("MainWindow", "Search For (Extension)"))
        self.t1t3l_6.setText(_translate("MainWindow", "Replace With (Extension)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.t1t3), _translate("MainWindow", "Bulk Rename Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_1), _translate("MainWindow", "Modifying Tools"))
        self.t2t1l_2.setText(_translate("MainWindow", "Energy to Extract"))
        self.t2t1l_4.setText(_translate("MainWindow", "Move Unique Files?"))
        self.t2t1l_1.setText(_translate("MainWindow", "Directory"))
        self.t2t1l_3.setText(_translate("MainWindow", "Search Recursively?"))
        self.t2t1l_5.setText(_translate("MainWindow", "Supress Duplicates?"))
        self.t2t1CB_1.setItemText(0, _translate("MainWindow", "HF"))
        self.t2t1CB_1.setItemText(1, _translate("MainWindow", "MP2"))
        self.t2t1CB_2.setItemText(0, _translate("MainWindow", "False"))
        self.t2t1CB_2.setItemText(1, _translate("MainWindow", "True"))
        self.t2t1CB_3.setItemText(0, _translate("MainWindow", "False"))
        self.t2t1CB_3.setItemText(1, _translate("MainWindow", "True"))
        self.t2t1CB_4.setItemText(0, _translate("MainWindow", "False"))
        self.t2t1CB_4.setItemText(1, _translate("MainWindow", "True"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.t2t1), _translate("MainWindow", "Single Point Energy"))
        self.t2t2l_1.setText(_translate("MainWindow", "Directory"))
        self.t2t2l_2.setText(_translate("MainWindow", "Search Recursively?"))
        self.t2t2CB_2.setItemText(0, _translate("MainWindow", "False"))
        self.t2t2CB_2.setItemText(1, _translate("MainWindow", "True"))
        self.t2t2l_3.setText(_translate("MainWindow", "Status of Jobs"))
        self.t2t2CB_1.setItemText(0, _translate("MainWindow", "Successful"))
        self.t2t2CB_1.setItemText(1, _translate("MainWindow", "Sucessful and Failed"))
        self.t2t2l_4.setText(_translate("MainWindow", "Sort files by"))
        self.t2t2CB_3.setItemText(0, _translate("MainWindow", "Filename"))
        self.t2t2CB_3.setItemText(1, _translate("MainWindow", "Electronic"))
        self.t2t2CB_3.setItemText(2, _translate("MainWindow", "Enthalpy"))
        self.t2t2CB_3.setItemText(3, _translate("MainWindow", "Free Energy"))
        self.t2t2l_5.setText(_translate("MainWindow", "Relative energies?"))
        self.t2t2CB_4.setItemText(0, _translate("MainWindow", "False"))
        self.t2t2CB_4.setItemText(1, _translate("MainWindow", "True"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.t2t11), _translate("MainWindow", "Thermochemical Data"))
        self.t2t3l_1.setText(_translate("MainWindow", "Directory"))
        self.t2t3l_4.setText(_translate("MainWindow", "IR-HWHM"))
        self.t2t3l_3.setText(_translate("MainWindow", "Wavenumber"))
        self.t2t3l_2.setText(_translate("MainWindow", "Step Size"))
        self.t2t3CB_1.setItemText(0, _translate("MainWindow", "Harmonic"))
        self.t2t3CB_1.setItemText(1, _translate("MainWindow", "Anharmonic"))
        self.t2t3CB_2.setItemText(0, _translate("MainWindow", "True"))
        self.t2t3CB_2.setItemText(1, _translate("MainWindow", "False"))
        self.t2t3l_5.setText(_translate("MainWindow", "Frequency Type"))
        self.t2t3l_6.setText(_translate("MainWindow", "Relative Intensity"))
        self.t2t3l_7.setText(_translate("MainWindow", "to Wavenumber"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.t2t3), _translate("MainWindow", "Computed Spectrum"))
        self.t2t4l_3.setText(_translate("MainWindow", "Rotation (Deg)"))
        self.t2t4CB_1.setItemText(0, _translate("MainWindow", "X"))
        self.t2t4CB_1.setItemText(1, _translate("MainWindow", "Y"))
        self.t2t4CB_1.setItemText(2, _translate("MainWindow", "Z"))
        self.t2t4l_2.setText(_translate("MainWindow", "Rotation Axis"))
        self.t2t4l_1.setText(_translate("MainWindow", "Directory"))
        self.t2t4PB_1.setText(_translate("MainWindow", "Select File"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.t2t4), _translate("MainWindow", "3D Rotation"))
        self.t2t5CB_2.setItemText(0, _translate("MainWindow", "Successful"))
        self.t2t5CB_2.setItemText(1, _translate("MainWindow", "Sucessful and Failed"))
        self.t2t5CB_1.setItemText(0, _translate("MainWindow", ".gjf"))
        self.t2t5CB_1.setItemText(1, _translate("MainWindow", ".log"))
        self.t2t5l_2.setText(_translate("MainWindow", "Status of Jobs"))
        self.t2t5l_1.setText(_translate("MainWindow", "Directory"))
        self.t2t5l_3.setText(_translate("MainWindow", "File Type"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.t2t5), _translate("MainWindow", "Geometry and Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Extraction Tools"))
        self.t3PQB_3.setItemText(0, _translate("MainWindow", "Do not save"))
        self.t3PQB_3.setItemText(1, _translate("MainWindow", "Same directory"))
        self.t3PQB_3.setItemText(2, _translate("MainWindow", "/scratch/rwf"))
        self.t3PQB_3.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.t1l7_2.setText(_translate("MainWindow", "Processors"))
        self.t1l8_2.setText(_translate("MainWindow", "Memory (MB)"))
        self.t3PQB_2.setItemText(0, _translate("MainWindow", "Do not save"))
        self.t3PQB_2.setItemText(1, _translate("MainWindow", "Same directory"))
        self.t3PQB_2.setItemText(2, _translate("MainWindow", "/scratch/scr"))
        self.t3PQB_2.setItemText(3, _translate("MainWindow", "Same & Nosave"))
        self.t1l10_2.setText(_translate("MainWindow", "Multiplicity"))
        self.t1l5_2.setText(_translate("MainWindow", "Username"))
        self.t3PQB_1.setItemText(0, _translate("MainWindow", "Do not save"))
        self.t3PQB_1.setItemText(1, _translate("MainWindow", "Same directory"))
        self.t3PQB_1.setItemText(2, _translate("MainWindow", "/scratch/chk"))
        self.t1l9_2.setText(_translate("MainWindow", "Charge"))
        self.t3PLE_1.setText(_translate("MainWindow", "jrjfeath"))
        self.t1l2_2.setText(_translate("MainWindow", "Checkpoint File"))
        self.t1l4_2.setText(_translate("MainWindow", "Read Write File"))
        self.t1l3_2.setText(_translate("MainWindow", "Scratch File"))
        self.t3PQB_4.setItemText(0, _translate("MainWindow", "# opt pm7"))
        self.t1l4_3.setText(_translate("MainWindow", "Basis set"))
        self.t3PPTE_1.setPlainText(_translate("MainWindow", "# opt pm7\n"
"# opt=tight hf/6-31g\n"
"# opt b3lyp/6-311++G(d,p)\n"
"# freq b3lyp/6-311++G(d,p)\n"
"# opt freq b3lyp/6-311++G(d,p)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Preferences"))
        self.Console.setPlainText(_translate("MainWindow", "Welcome to the latest edition of Feather Labs Suite!\n"
"This suite of programs was developed for use with Gaussian calculations.\n"
"This program can be updated by selecting: \"Check for updates\" under \"File\" in the menu.\n"
"Any recommendations, errors, or concerns should be submitted at: \n"
"https://github.com/jrjfeath/Feather_Labs_Suite/issues"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.pushButton.setShortcut(_translate("MainWindow", "Shift+Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_Change_Log.setText(_translate("MainWindow", "Change Log"))
        self.action_Check_for_updates.setText(_translate("MainWindow", "Check for updates"))
        self.action_Exit.setText(_translate("MainWindow", "Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
